/**
 * This file is automatically generated from `/config/route.mustache`,
 * DO NOT modify this file directly.
 */

import module from './module';

module.config(/* @ngInject */($futureStateProvider, $locationProvider, $urlRouterProvider) => {
    const futureStates = [
        {
            stateName: 'dashboard',
            url: '/dashboard',
            type: 'asyncState',
        },
        {
            stateName: 'home',
            url: '/',
            type: 'asyncState',
        },
        {
            stateName: 'profile',
            url: '/profile',
            type: 'asyncState',
        },
    ];

    futureStates.forEach((futureState) => {
        $futureStateProvider.futureState(futureState);
    });

    $futureStateProvider.stateFactory('asyncState', /* @ngInject */($q, futureState) => {
        const d = $q.defer();

        function moduleResolve(mod) {
            const state = {
                name: futureState.stateName,
                url: futureState.url,
                controller: `${futureState.stateName}Ctrl`,
                template: mod.template,
            };
            d.resolve(state);
        }

        switch (futureState.stateName) {
        case 'dashboard':
            require.ensure(['./dashboard/index'], (require) => {
                moduleResolve(require('./dashboard/index'));
            });
            break;
        case 'home':
            require.ensure(['./home/index'], (require) => {
                moduleResolve(require('./home/index'));
            });
            break;
        case 'profile':
            require.ensure(['./profile/index'], (require) => {
                moduleResolve(require('./profile/index'));
            });
            break;
        default:
            break;
        }

        return d.promise;
    });

    /**
    * looks like futureState is not compatible with urlRouterProvider.otherwise
    */
    $urlRouterProvider.otherwise('/');

    // 启用 html5 history
    $locationProvider.html5Mode(true);
});
